# docker-compose.prod.yml - Production deployment với Ollama tích hợp

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - INSTALL_OLLAMA=true
        - DOWNLOAD_MODELS_ON_START=true
        - AUTO_SETUP_ENABLED=true
    container_name: chatbot_backend
    ports:
      - "8000:8000"      # Backend API
      - "11434:11434"    # Ollama API
    volumes:
      - ./data:/app/data
      - ./ollama_models:/root/.ollama
      - ./logs:/app/logs
    environment:
      - INSTALL_OLLAMA=true
      - DOWNLOAD_MODELS_ON_START=true
      - AUTO_SETUP_ENABLED=true
      - PREFERRED_AI_PROVIDER=ollama
      - OLLAMA_MODEL=gemma2:1b
      - OLLAMA_HOST=0.0.0.0:11434
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 8G      # Ollama cần nhiều RAM
          cpus: '4.0'
        reservations:
          memory: 4G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s  # Thời gian dài hơn cho setup
    restart: unless-stopped
    networks:
      - chatbot_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=https://chat.hungpnh.dev
        - REACT_APP_WS_URL=wss://chat.hungpnh.dev
        - NODE_ENV=production
    container_name: chatbot_frontend
    ports:
      - "3000:3000"      # Frontend
    environment:
      - REACT_APP_API_URL=https://chat.hungpnh.dev
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - chatbot_network
    depends_on:
      - backend

volumes:
  chatbot_data:
    driver: local
  ollama_models:
    driver: local
  chatbot_logs:
    driver: local

networks:
  chatbot_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16